name:                haskell-id-containers
version:             0.0.1
github:              "sourcedennis/haskell-id-containers"
license:             BSD3
author:              "Dennis Sprokholt"
maintainer:          "me@dennis.life"
copyright:           "2020 Dennis Sprokholt"

extra-source-files:
- README.md
- LICENSE

description:         Please see the README on GitHub at <https://github.com/sourcedennis/haskell-id-containers#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers >= 0.6 && < 0.7
  - unordered-containers >= 0.2.10 && < 0.2.11
  - hashable >= 1.3 && < 1.4
  exposed-modules:
  - Data.IdHashSet
  - Data.IdList
  - Data.IdSet

tests:
  haskell-id-containers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-id-containers
    - containers >= 0.6 && < 0.7
    - unordered-containers >= 0.2.10 && < 0.2.11
    - hashable >= 1.3 && < 1.4
    - tasty
    - tasty-hunit
    - tasty-quickcheck
