name:                id-containers
version:             0.0.1
github:              "sourcedennis/haskell-id-containers"
license:             BSD3
author:              "Dennis Sprokholt"
maintainer:          "me@dennis.life"
copyright:           "2021 Dennis Sprokholt"

extra-source-files:
- README.md
- resources/abc_graph.png
- LICENSE

description:         Please see the README on GitHub at <https://github.com/sourcedennis/haskell-id-containers#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - deepseq >= 1.2 && < 1.5
  - containers >= 0.6 && < 0.7
  - unordered-containers >= 0.2.10 && < 0.2.11
  - vector >= 0.12 && < 0.13
  - hashable >= 1.2 && < 1.4
  exposed-modules:
  - Data.IdHashSet
  - Data.IdList
  - Data.IdSet

tests:
  id-containers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - id-containers
    - containers >= 0.6 && < 0.7
    - unordered-containers >= 0.2.10 && < 0.2.11
    - hashable >= 1.2 && < 1.4
    - tasty >= 1.2.2 && < 1.4
    - tasty-hunit >= 0.10 && < 0.11
    - tasty-quickcheck >= 0.10 && < 0.11
